@startuml Data Viewer

interface UIWidget {
  + print()
}

class App {
  - window_list
  - window
  - context
  + setup()
  + process_events()
  + update()
  + close()
}

class GlobalWindow {
  - widget_list
  + add_widget()
  + display()
}

struct SensorData {
  + time
  + acceleration
  + rotation
  + magnetic
}

class NetworkReceiver {
  + display()
  - update_data()
  - hostname
  - ssid
  - wireless_enabled
  - networkmanager_proxy
  - data_client
}

class NetworkManagerProxy {
  + wireless_enabled()
  + hostname()
  + network_name()
  - get_wireless_device_path()
  - set_wireless_device()
  - networkmanager_proxy
  - wireless_device_proxy
  - settings_proxy
}

class NetworkManagerDBUSProxy {
  + read_parameter()
  + read_type()
  - dbus_proxy
}

class AsyncServer {
  + do_receive()
  + handle_read()
  - socket
  - data
}

class DataClient {
  - io_context
  - server
}

class Graph {
  - recording
  - data_queue
  - acceleration: vector
  - rotation: vector
  - magnetic: vector
  + print()
  + start_recording()
  + stop_recording()
  + add_point()
  + clear_graph()
}

class Visualisation {
  - model
  - background
  - orientation
}

class ControlPanel {
  + print()
}

class MadgFilter {
  + currentData
  + previousData
  + filter()
}

App *-- GlobalWindow
GlobalWindow -- Visualisation
GlobalWindow -- NetworkReceiver
GlobalWindow -- Graph
GlobalWindow -- ControlPanel

NetworkReceiver -- NetworkManagerProxy
NetworkReceiver -- DataClient
DataClient -- AsyncServer
NetworkManagerProxy -- NetworkManagerDBUSProxy

UIWidget --> NetworkReceiver
UIWidget --> ControlPanel
UIWidget --> Graph

Graph "1" *-- "0..*" SensorData

MadgFilter -- NetworkReceiver
